version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./db_data:/var/lib/postgresql/data/

  # app:
  #   build: ./app
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     DATABASE_URL: postgres://myuser:mypassword@db:5432/mydatabase
  #   volumes:
  #     - ./app:/app
  #   depends_on:
  #     - db

volumes:
  db_data:
